# Generated by Django 4.2.13 on 2024-06-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_message_alter_booking_requested_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='requested_time',
            field=models.TimeField(),
        ),
    ]
