# Generated by Django 4.2.13 on 2024-06-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_requested_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='message',
            field=models.TextField(blank=True, default='no message'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='requested_time',
            field=models.TimeField(help_text='Available between 13:00 - 23:00'),
        ),
    ]
