# Generated by Django 4.2.13 on 2024-06-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_requested_time_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Awaiting', 'Awaiting'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Expired', 'Expired')], default='Awaiting'),
        ),
    ]
