# Generated by Django 4.2.13 on 2024-06-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_phone_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Awaiting', 'Awaiting'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending'),
        ),
    ]
