# Generated by Django 4.2.13 on 2024-06-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_category_alter_comment_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(0, 'Restaurant'), (1, 'Market'), (2, 'General')]),
        ),
    ]
