# Generated by Django 4.2.13 on 2024-06-25 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_title_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='description',
        ),
    ]
