# Generated by Django 4.2.13 on 2024-07-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sold',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
